from __future__ import annotations

import re
import shutil
import subprocess
import textwrap
import zipfile
from pathlib import Path

from .workspace import _load_state, _load_yaml, _save_state, _today, active_target


def _title_from_context(context_path: Path) -> str:
    if not context_path.exists():
        return "Untitled Paper"
    text = context_path.read_text(encoding="utf-8")
    match = re.search(r"## Title\s+(.+)", text)
    return match.group(1).strip() if match else "Untitled Paper"


def _outline_filename_map(outline_path: Path) -> dict[str, str]:
    if not outline_path.exists():
        return {}
    mapping: dict[str, str] = {}
    text = outline_path.read_text(encoding="utf-8")
    for match in re.finditer(r"###\s+.+?([A-Za-z /-]+)\s+\(filename:\s*([^)]+\.tex)\)", text):
        heading = match.group(1).strip().lower()
        filename = match.group(2).strip()
        mapping[heading] = filename
    return mapping


def _ordered_section_inputs(target_root: Path, audience: str) -> list[str]:
    sections_root = target_root / "sections"
    outline_map = _outline_filename_map(target_root / "outline.md")
    ordered: list[str] = []
    custom_candidates = {
        "abstract": outline_map.get("abstract"),
        "introduction": outline_map.get("introduction"),
        "related work": outline_map.get("related work") or outline_map.get("literature review"),
        "background": outline_map.get("background") or outline_map.get("model setup"),
        "methodology": outline_map.get("methodology") or outline_map.get("method"),
        "theory": outline_map.get("theory"),
        "experiments": outline_map.get("experiments") or outline_map.get("empirics"),
        "conclusion": outline_map.get("conclusion"),
        "appendix proofs": outline_map.get("appendix proofs"),
        "appendix experiments": outline_map.get("appendix experiments"),
    }
    default_names = [
        custom_candidates["abstract"] or "abstract.tex",
        custom_candidates["introduction"] or "introduction.tex",
        custom_candidates["related work"] or "related_work.tex",
        custom_candidates["background"] or "background.tex",
        custom_candidates["methodology"] or "methodology.tex",
        custom_candidates["theory"] or "theory.tex",
        custom_candidates["experiments"] or ("experiments.tex" if audience == "ml" else "empirics.tex"),
        custom_candidates["conclusion"] or "conclusion.tex",
        custom_candidates["appendix proofs"] or "appendix_proofs.tex",
        custom_candidates["appendix experiments"] or "appendix_experiments.tex",
    ]
    for name in default_names:
        if (sections_root / name).exists():
            ordered.append(name)
    remaining = sorted(
        path.name for path in sections_root.glob("*.tex") if path.name not in ordered and path.name not in {"abstract.tex"}
    )
    ordered.extend(remaining)
    return ordered


def assemble_paper(repo_root: Path, *, compile_pdf: bool = False, target_name: str | None = None) -> Path:
    target = target_name or active_target(repo_root)
    target_root = repo_root / "paper" / target
    target_data = _load_yaml(target_root / "target.yaml")
    title = _title_from_context(repo_root / "paper/shared/context.md")
    audience = str(target_data.get("audience", "ml"))
    ordered_sections = _ordered_section_inputs(target_root, audience)
    section_inputs: list[str] = []
    appendix_inputs: list[str] = []
    for filename in ordered_sections:
        line = f"\\input{{sections/{Path(filename).stem}}}"
        if filename.startswith("appendix_"):
            appendix_inputs.append(line)
        elif filename != "abstract.tex":
            section_inputs.append(line)

    abstract_block = "\\input{sections/abstract}\n" if (target_root / "sections/abstract.tex").exists() else "% Abstract pending\n"
    bibliography_style = target_data.get("bibstyle") or "plainnat"
    template_name = target_data.get("template", "custom")
    main_tex = textwrap.dedent(
        f"""\
        % Generated by Pepper's deterministic assembler.
        % Target template: {template_name}
        % Copy venue style files into `.pepper/templates/{template_name}/` before final compilation.
        \\documentclass{{article}}
        \\usepackage[utf8]{{inputenc}}
        \\usepackage[T1]{{fontenc}}
        \\usepackage{{amsmath,amssymb,amsthm}}
        \\usepackage{{graphicx}}
        \\usepackage{{booktabs}}
        \\usepackage{{threeparttable}}
        \\usepackage{{natbib}}
        \\usepackage{{hyperref}}
        \\title{{{title}}}
        \\author{{Anonymous Author(s)}}
        \\date{{}}
        \\begin{{document}}
        \\maketitle
        \\begin{{abstract}}
        {abstract_block.rstrip()}
        \\end{{abstract}}
        {chr(10).join(section_inputs)}
        \\bibliographystyle{{{bibliography_style}}}
        \\bibliography{{references}}
        """
    )
    if appendix_inputs:
        main_tex += "\n\\appendix\n" + "\n".join(appendix_inputs) + "\n"
    main_tex += "\\end{document}\n"
    main_path = target_root / "main.tex"
    main_path.write_text(main_tex, encoding="utf-8")

    state = _load_state(repo_root)
    state.setdefault("targets", {}).setdefault(target, {})["stage"] = "drafting"
    _save_state(repo_root, state)

    if compile_pdf:
        _run_latex_sequence(target_root)
    return main_path


def _copy_tree_contents(source: Path, destination: Path) -> None:
    if not source.exists():
        return
    destination.mkdir(parents=True, exist_ok=True)
    for path in sorted(source.rglob("*")):
        relative = path.relative_to(source)
        target = destination / relative
        if path.is_dir():
            target.mkdir(parents=True, exist_ok=True)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(path, target)


def _run_latex_sequence(target_root: Path) -> None:
    commands = (
        ["pdflatex", "main.tex"],
        ["bibtex", "main"],
        ["pdflatex", "main.tex"],
        ["pdflatex", "main.tex"],
    )
    for command in commands:
        subprocess.run(command, cwd=target_root, check=True, capture_output=True, text=True)


def camera_ready(repo_root: Path, *, compile_pdf: bool = False, target_name: str | None = None) -> Path:
    target = target_name or active_target(repo_root)
    target_root = repo_root / "paper" / target
    if not (target_root / "main.tex").exists():
        assemble_paper(repo_root, compile_pdf=False, target_name=target)
    camera_root = target_root / "camera-ready"
    camera_root.mkdir(parents=True, exist_ok=True)
    shutil.copy2(target_root / "main.tex", camera_root / "main.tex")
    if (target_root / "references.bib").exists():
        shutil.copy2(target_root / "references.bib", camera_root / "references.bib")
    _copy_tree_contents(target_root / "figures", camera_root / "figures")

    target_data = _load_yaml(target_root / "target.yaml")
    template_name = str(target_data.get("template", ""))
    if template_name:
        _copy_tree_contents(repo_root / f".pepper/templates/{template_name}", camera_root)

    verification = textwrap.dedent(
        f"""\
        # Camera-Ready Verification

        - Target: `{target}`
        - Venue: `{target_data.get('venue', 'unknown')}`
        - Generated: `{_today()}`
        - Main manuscript: `main.tex`
        - Bibliography copied: `{'yes' if (camera_root / 'references.bib').exists() else 'no'}`
        """
    )
    (camera_root / "VERIFICATION.md").write_text(verification, encoding="utf-8")
    submission_notes = textwrap.dedent(
        """\
        # Submission Notes

        Review the generated package, confirm that official venue style files are present,
        and resolve any remaining placeholders before submission.
        """
    )
    (camera_root / "SUBMISSION_NOTES.md").write_text(submission_notes, encoding="utf-8")

    if compile_pdf:
        _run_latex_sequence(camera_root)

    zip_path = target_root / "submission.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(camera_root.rglob("*")):
            if path.is_file():
                archive.write(path, path.relative_to(camera_root))

    state = _load_state(repo_root)
    state.setdefault("targets", {}).setdefault(target, {})["stage"] = "camera-ready"
    _save_state(repo_root, state)
    return zip_path
